CREATE TABLE IF NOT EXISTS etl_watermarks (
    table_name VARCHAR(100) PRIMARY KEY,
    watermark_value TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01 00:00:00+00',
    last_run TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
